
sudo: required
services:
  - docker
before_install:
  - docker build -t node/test .
script:
  - docker images node/test
after_success:
  - docker login -e="$antoniobasasjr@gmail.com" -u="$junexbasas" -p="$PP@ssw00rd";
  - docker push node/test;
    


