sudo: required
services:
  - docker
before_script:
  - docker build -t node/test .
after_script:
  - docker images node/test
before_deploy:
  - docker login --username=junexbasas --password=PP@ssw00rd
  - docker tag node/test junexbasas/node/test:v1
  - docker images
deploy:
provider: script
script: - docker push junexbasas/node/test
on:
branch: master
  
  