language: bash
sudo: required

service:
  - docker

script:
  - docker build -t node:v1 .
  # - docker tag node:alpine noded/v:1
  # - docker login --username=junexbasas --password=PP@ssw00rd
  # - docker push noded/v

  after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$antoniobasasjr@gmail.com" -u="$junexbasas" -p="$PP@ssw00rd";
      docker push node:v1;
      fi