
sudo: required
services:
  - docker
before_install:
  - docker build -t node/test .
script:
  - docker images node/test
after_success:
  - docker login --username=junexbasas --password=PP@ssw00rd
  - docker tag node/test junexbasas/node/test:v1
  - docker images
deploy:
  - docker push junexbasas/node/test