
sudo: required
services:
  - docker
before_install:
  - docker build -t node/test .
script:
  - docker images node/test
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$antoniobasasjr@gmail.com" -u="$junexbasas" -p="$PP@ssw00rd";
    docker push node/test;
    fi


