language: node_js

services:
  - docker

before_install:
- docker pull node:alpine
- docker run -d -p 0.0.0.0:80:80 --name testsample node:alpine /bin/ash -c "cd /home/node/testsample ; git clone https://github.com/antoniobasasjr/testsample.git /home/node/testsample; npm install /home/node/testsample;"
- docker ps -a


